# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('industry', models.CharField(blank=True, max_length=50, null=True)),
                ('vertical', models.CharField(blank=True, max_length=50, null=True)),
                ('total_brr', models.FloatField(blank=True, null=True)),
                ('annual_revenue', models.FloatField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField()),
                ('dandb_revenue', models.FloatField(blank=True, null=True)),
                ('dandb_total_employees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('market', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=10, null=True)),
                ('zayo_network_status', models.CharField(max_length=50)),
                ('net_classification', models.CharField(max_length=20)),
                ('building_type', models.CharField(max_length=50)),
                ('network_proximity', models.FloatField(blank=True, null=True)),
                ('estimated_build_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpq',
            fields=[
                ('cpq_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('product_group', models.CharField(max_length=50)),
                ('x36_mrc_list', models.FloatField(blank=True, null=True)),
                ('x36_nrr_list', models.FloatField(blank=True, null=True)),
                ('x36_npv_list', models.FloatField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.Account')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('base_cost', models.FloatField()),
                ('distance_less_500_ft', models.FloatField()),
                ('distance_greater_500_ft', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('opportunity_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(max_length=50)),
                ('is_closed', models.BooleanField()),
                ('is_won', models.BooleanField()),
                ('created_date', models.DateField()),
                ('term_in_months', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('opportunity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('product_group', models.CharField(max_length=50)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.Account')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('total_mrr', models.FloatField(blank=True, null=True)),
                ('next_mrc', models.FloatField(blank=True, null=True)),
                ('product_group', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('building_id', models.CharField(blank=True, max_length=15, null=True)),
                ('street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=5, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Account')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Building')),
            ],
        ),
    ]
